// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/dart_types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_and_download_updates`, `get_update_manager`

Future<void> initVelopack({required String url}) =>
    VelopackRustLib.instance.api.crateApiVelopackInitVelopack(url: url);

Future<bool> isUpdateAvailable() =>
    VelopackRustLib.instance.api.crateApiVelopackIsUpdateAvailable();

Future<UpdateInfo?> getLatestUpdateInfo() =>
    VelopackRustLib.instance.api.crateApiVelopackGetLatestUpdateInfo();

Future<String> currentVersion() =>
    VelopackRustLib.instance.api.crateApiVelopackCurrentVersion();

Stream<int> checkAndDownloadUpdatesWithProgress() =>
    VelopackRustLib.instance.api
        .crateApiVelopackCheckAndDownloadUpdatesWithProgress();

Future<void> updateAndRestart() =>
    VelopackRustLib.instance.api.crateApiVelopackUpdateAndRestart();

Future<void> updateAndExit() =>
    VelopackRustLib.instance.api.crateApiVelopackUpdateAndExit();

Future<void> waitExitThenUpdate(
        {required bool silent, required bool restart}) =>
    VelopackRustLib.instance.api
        .crateApiVelopackWaitExitThenUpdate(silent: silent, restart: restart);
